# Generated by Django 3.1.2 on 2021-05-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=64)),
                ('types', models.CharField(max_length=64)),
                ('date', models.DateField()),
            ],
        ),
    ]
